#!/usr/bin/env bash

set -e -u -o pipefail

clear

file=$1 line=$2 flags=${3-}

all=false errexit=false xtrace=false
bash=false coffee=false js=false node=false perl=false python=false ruby=false

for flag in ${flags//,/ }; do
  var=${flag#--}
  printf -v "$var" true
done

code=$(
  cat "$file" |
  perl -e '
    $n = shift(@ARGV);
    $i = 0;
    $code = "";
    $found = 0;
    while ($l = <>) {
      $code .= $l;
      $found = 1 if ++$i >= $n;
      if ($l !~ /\S/) {
        if ($found) {
          $code =~ s/\n+\z/\n/;
          print $code;
          exit 0;
        }
        $code = "";
      }
    }
    print $code;
  ' "$line" |
  perl -pe 's/^\ {4}//gm' |
  perl -p0e 's/\A\s*(.*?)\s*\z/$1/'
)

[[ $code ]] || exit 0

if [[ $code == \$* ]]; then
  code=$(perl -pe 's/^[\$\>]\ //m' <<< "$code")
  bash=true

elif [[ $code =~ ^\#\ (bash|coffee|js|node|perl|python|ruby) ]]; then
  var=${BASH_REMATCH[1]}
  printf -v "$var" true
  code=$(tail -n+2 <<<"$code")

else
  all=true
  code=$(
    cat "$file" |
    perl -pe 's/^\ {4}//gm' |
    perl -p0e 's/\A\s*(.*?)\s*\z/$1/'
  )
  bash=true
fi

line=$(printf "%.0s-" {1..80})

if ! $all; then
  cat <<...
$line
$code
...
fi

echo "$line"

echo "$code" | (
  if $bash; then
    if $errexit; then
      if $xtrace; then
        bash -e -
      else
        bash -ex -
      fi
    else
      bash -
    fi
  elif $perl; then perl -Mv5.12 -
  elif $python; then python -
  elif $ruby; then ruby -
  elif $js || $node; then
    cat > code.js
    node code.js
  elif $coffee; then
    cat > code.coffee
    coffee code.coffee
  fi
)

rc=$?

echo "$line"

if [[ $rc -ne 0 ]]; then
  echo "exit status -> $rc"
fi
